=== accelerator-blueprints/orion/packages/app/src/validations/schemas/assessment.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://www.nearform.com/schemas/assessment.json",
  "title": "Assessment schema",
  "description": "Validates assessment data",
  "type": "object",
  "properties": {
    "name": {
      "$ref": "definitions.json#/definitions/name"
    },
    "key": {
      "$ref": "definitions.json#/definitions/key"
    },
    "guidance": {
      "$ref": "definitions.json#/definitions/guidance"
    },
    "orderIndex": {
      "type": "number",
      "minimum": 0
    },
    "logoAsset": {
      "type": "string"
    },
    "shortDescription": {
      "type": "string"
    },
    "pillars": {
      "type": "array",
      "uniqueItems": true,
      "items": [
        {
          "$ref": "definitions.json#/definitions/pillar"
        }
      ]
    }
  },
  "required": [
    "name",
    "key",
    "pillars",
    "orderIndex",
    "shortDescription"
  ]
}

=== accelerator-blueprints/orion/packages/efqm-theme/assessments/business-matrix-advanced.json
{
  "key": "efqm-2020-advanced",
  "name": "business matrix advanced",
  "orderIndex": 3,
  "logoAsset": "assess-3-img",
  "shortDescription": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi interdum sapien et ipsum pellentesque, ut fringilla eros scelerisque. Mauris ex ex, viverra pharetra cursus gravida, vulputate ac velit.",
  "pillars": []
}
